// Code generated by protoc-gen-go. DO NOT EDIT.
// source: godfs.proto

package godfs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FUnit struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Md5                  string   `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FUnit) Reset()         { *m = FUnit{} }
func (m *FUnit) String() string { return proto.CompactTextString(m) }
func (*FUnit) ProtoMessage()    {}
func (*FUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96caf3db100dde2, []int{0}
}

func (m *FUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FUnit.Unmarshal(m, b)
}
func (m *FUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FUnit.Marshal(b, m, deterministic)
}
func (m *FUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FUnit.Merge(m, src)
}
func (m *FUnit) XXX_Size() int {
	return xxx_messageInfo_FUnit.Size(m)
}
func (m *FUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_FUnit.DiscardUnknown(m)
}

var xxx_messageInfo_FUnit proto.InternalMessageInfo

func (m *FUnit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FUnit) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *FUnit) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Block struct {
	Data                 *any.Any `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96caf3db100dde2, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type DFile struct {
	Data                 *any.Any `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Blocks               []*Block `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	FsPath               string   `protobuf:"bytes,3,opt,name=fsPath,proto3" json:"fsPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DFile) Reset()         { *m = DFile{} }
func (m *DFile) String() string { return proto.CompactTextString(m) }
func (*DFile) ProtoMessage()    {}
func (*DFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96caf3db100dde2, []int{2}
}

func (m *DFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DFile.Unmarshal(m, b)
}
func (m *DFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DFile.Marshal(b, m, deterministic)
}
func (m *DFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DFile.Merge(m, src)
}
func (m *DFile) XXX_Size() int {
	return xxx_messageInfo_DFile.Size(m)
}
func (m *DFile) XXX_DiscardUnknown() {
	xxx_messageInfo_DFile.DiscardUnknown(m)
}

var xxx_messageInfo_DFile proto.InternalMessageInfo

func (m *DFile) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DFile) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *DFile) GetFsPath() string {
	if m != nil {
		return m.FsPath
	}
	return ""
}

type Resp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96caf3db100dde2, []int{3}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Resp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*FUnit)(nil), "godfs.FUnit")
	proto.RegisterType((*Block)(nil), "godfs.Block")
	proto.RegisterType((*DFile)(nil), "godfs.DFile")
	proto.RegisterType((*Resp)(nil), "godfs.Resp")
}

func init() { proto.RegisterFile("godfs.proto", fileDescriptor_c96caf3db100dde2) }

var fileDescriptor_c96caf3db100dde2 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x24, 0x4d, 0x36, 0xd8, 0x17, 0x0f, 0xb2, 0x88, 0xc4, 0x9e, 0x42, 0xf0, 0x90, 0xd3, 0x56,
	0x2a, 0x7e, 0x40, 0x45, 0x7a, 0x13, 0x64, 0xc1, 0x0f, 0xd8, 0x34, 0x9b, 0x35, 0x98, 0xee, 0x2b,
	0xbe, 0xed, 0xa1, 0x7e, 0xbd, 0xe4, 0x65, 0xed, 0xdd, 0xdb, 0xcc, 0x7b, 0xc3, 0xcc, 0x30, 0x50,
	0x38, 0xec, 0x7a, 0x52, 0xc7, 0x6f, 0x0c, 0x28, 0x05, 0x93, 0xd5, 0xbd, 0x43, 0x74, 0xa3, 0x5d,
	0xf3, 0xb1, 0x3d, 0xf5, 0x6b, 0xe3, 0xcf, 0xb3, 0xa2, 0xde, 0x82, 0xd8, 0x7d, 0xf8, 0x21, 0x48,
	0x09, 0x99, 0x37, 0x07, 0x5b, 0x26, 0x55, 0xd2, 0x2c, 0x35, 0x63, 0x79, 0x03, 0xe9, 0xa1, 0x7b,
	0x2e, 0x17, 0x7c, 0x9a, 0xe0, 0xa4, 0xa2, 0xe1, 0xc7, 0x96, 0x69, 0x95, 0x34, 0x99, 0x66, 0x5c,
	0xbf, 0x81, 0x78, 0x19, 0x71, 0xff, 0x25, 0x1b, 0xc8, 0x3a, 0x13, 0x0c, 0x5b, 0x14, 0x9b, 0x5b,
	0x35, 0xa7, 0xaa, 0xbf, 0x54, 0xb5, 0xf5, 0x67, 0xcd, 0x0a, 0xb9, 0x82, 0xab, 0x11, 0xf7, 0x26,
	0x0c, 0xe8, 0xa3, 0xfb, 0x85, 0xd7, 0x08, 0xe2, 0x75, 0x37, 0x8c, 0xf6, 0x1f, 0x76, 0x0f, 0x90,
	0xb7, 0x53, 0x03, 0x2a, 0x17, 0x55, 0xda, 0x14, 0x9b, 0x6b, 0x35, 0x8f, 0xc0, 0xb5, 0x74, 0xfc,
	0xc9, 0x3b, 0xc8, 0x7b, 0x7a, 0x37, 0xe1, 0x93, 0xdb, 0x2f, 0x75, 0x64, 0xf5, 0x23, 0x64, 0xda,
	0xd2, 0x71, 0xfa, 0x53, 0x30, 0xe1, 0x44, 0x9c, 0x28, 0x74, 0x64, 0xbc, 0x02, 0xb9, 0xcb, 0x0a,
	0xe4, 0xda, 0x9c, 0x3b, 0x3c, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x29, 0x76, 0xee, 0x7a, 0x6c,
	0x01, 0x00, 0x00,
}
